=== gaps-closure/mules/xdcc_gen/schema/receiveISRMDetections_schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#", 
	"$id": "https://example.com/object1608293658.json", 
	"title": "Root", 
	"type": "array",
	"numElements": 25,
	"default": [],
	"items":{
		"$id": "#root/items", 
		"title": "Items", 
		"type": "object",
		"required": [
			"TGT_ISRM_ID",
			"alt",
			"bearing",
			"classification",
			"confidence",
			"lat",
			"lon",
			"speed"
		],
		"properties": {
			"TGT_ISRM_ID": {
				"$id": "#root/items/TGT_ISRM_ID", 
				"title": "Tgt_isrm_id", 
				"type": "string",
			        "maxLength": 32,
				"default": "",
				"examples": [
					"355586"
				],
				"pattern": "^.*$"
			},
			"alt": {
				"$id": "#root/items/alt", 
				"title": "Alt", 
				"type": "number",
				"examples": [
					1.1
				],
				"default": 0.0
			},
			"bearing": {
				"$id": "#root/items/bearing", 
				"title": "Bearing", 
				"type": "number",
				"examples": [
					237.98623638133768
				],
				"default": 0.0
			},
			"classification": {
				"$id": "#root/items/classification", 
				"title": "Classification", 
				"type": "string",
	                        "maxLength": 64,
				"default": "",
				"examples": [
					"person"
				],
				"pattern": "^.*$"
			},
			"confidence": {
				"$id": "#root/items/confidence", 
				"title": "Confidence", 
				"type": "number",
				"examples": [
					0.8435034155845642
				],
				"default": 0.0
			},
			"lat": {
				"$id": "#root/items/lat", 
				"title": "Lat", 
				"type": "number",
				"examples": [
					30.687774320048185
				],
				"default": 0.0
			},
			"lon": {
				"$id": "#root/items/lon", 
				"title": "Lon", 
				"type": "number",
				"examples": [
					-117.21310154166385
				],
				"default": 0.0
			},
			"speed": {
				"$id": "#root/items/speed", 
				"title": "Speed", 
				"type": "number",
				"examples": [
					112.92731367797232
				],
				"default": 0.0
			}
		}
	}

}

=== gaps-closure/mules/xdcc_gen/messages/recieveRDRDetections.json
[
    {
        "TGT_ISRM_ID": "355586",
        "alt": 0.0,
        "bearing": 237.98623638133768,
        "classification": "",
        "confidence": -1.0,
        "lat": 30.687774320048185,
        "lon": -117.21310154166385,
        "speed": 112.92731367797232
    },
    {
        "TGT_ISRM_ID": "293127",
        "alt": 0.0,
        "bearing": 50.26230304960208,
        "classification": "",
        "confidence": -1.0,
        "lat": 32.74936743790192,
        "lon": -117.11299499098978,
        "speed": 112.60642434450348
    }
]

=== gaps-closure/mules/xdcc_gen/messages/recieveEOIRDetections.json
[
    {
        "TGT_ISRM_ID": "355586",
        "alt": 0.0,
        "bearing": -1.0,
        "classification": "person\r",
        "confidence": 0.8435034155845642,
        "lat": 30.69738894691726,
        "lon": -117.19521803573252,
        "speed": -1.0
    },
    {
        "TGT_ISRM_ID": "293127",
        "alt": 0.0,
        "bearing": -1.0,
        "classification": "car\r",
        "confidence": 0.8304253816604614,
        "lat": 32.73780527115163,
        "lon": -117.12953061075143,
        "speed": -1.0
    }
]
